version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/prisma
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=file:./data/todo.db

  frontend:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
